### PR TITLE
Feature: use oao.json to manage some options

### PR DESCRIPTION
**Pull request by pedronauck**
Hi 😀,

I made just a simple change to can be possible to define some global options using a json config file instead of write always in the cli, as suggested on #44, but using a `oao.json` instead of put in a `package.json`, like lerna does.

For now, I put just the `--src` and `--ignoreSrc` option that can be defined. Remembering that user input options defined on cli will override the global on `oao.json`

With this change it's possible to create something like these:

```json
{
  "src": ["packages/*", "helpers/*"],
  "ignoreSrc": "others"
}
```

And I change to accept an array of globs too, instead just a string!

### CODE REVIEW

**Comment by guigrpa** [comment]
Hey, thanks for the PR! I'll check it out shortly.

Just one question up front, why an additional file instead of using package.json?

**Comment by pedronauck** [comment]
Thanks @guigrpa, I don't like to put a lot of configs on `package.json`, I think that it responsable to define things about the package, I prefer separate the concerns and put in a file that has just things about your concern. Can be more easy to put the eyes on project and find what you want. And how you mentioned lerna on the README, I think that you could follow it's path.

But if you guess that it's better put these config on `package.json`, I think that's a good idea too.

**Comment by guigrpa** [comment]
I think package.json might be better, yes. It's where you specify basic things of your package (in our case, the monorepo root package): name, entry point, build scripts, ... and with your PR things like subpackage directories, etc.

Other tools also put their config (some of them optionally) in there: Ava, Jest...

**Comment by pedronauck** [comment]
@guigrpa I made change and put config on `package.json` as you suggested, if you can check and deploy a new version, I need a lot these change in a big project on my work 🙏

**Comment by guigrpa** [comment]
Please check out v0.9.0 and tell me if it's OK. I tested it on a couple monorepos and seemed to work fine.

**Comment by guigrpa** [comment]
Thanks for the PR!!

**Comment by pedronauck** [comment]
I tested in my repo and everthing is fine, thanks @guigrpa for accept the pr too and congratulations for the package, I was waiting long time a good monorepo package, lerna for me it's a big messy! :v:

cheers

**Comment by ericclemmons** [comment]
Hey, I just wanted say **Thank you** for this addition!  I have `/examples/*` and `/packages/*` and this cleans up my repo greatly.

I've been using `oao` for a couple months now & it's been fantastic.  Great work!

**Comment by guigrpa** [comment]
You're welcome!

**Pull request merged**
