### PR TITLE
Adds ability to specify version increment non-interactively on cli

### PR DESCRIPTION
**Pull request by gordlea**
This will enable people to use oao as part of a continuous deployment environment, where selecting the next version on interactively isn't possible. 

#### Usage
```
oao publish --no-confirm --increment-version-by <major|minor|patch|rc|beta|alpha>
```

I'm open to feedback/changes to make this PR more consistent with the rest of the project if needed.

### CODE REVIEW

**Comment by gordlea** [comment]
Not sure why the build failed, i don't think it's related to my changes: 

```
'/home/travis/.nvm/versions/node/v8.1.0/lib/node_modules/.staging/http-signature-44735bc1/.dir-locals.el'
npm ERR! Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
```

**Comment by guigrpa** [comment]
Thanks for the PR! I'll review it asap; I think it's a really nice idea and contribution to the project.

As to the build error, I'm also unsure as to what's causing this. I haven't tried to build oao on Node 8.x, so will need to check locally. Thanks for your patience!

**Comment by gordlea** [comment]
It looks like it fails on installing yarn. It seems travis-ci now has yarn by default: https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn, I'll modify travis.yml and try again.

**Comment by gordlea** [comment]
@guigrpa Any timeline on getting this reviewed? I'd like to start using it on our CI build. Totally okay if you're too busy at the moment, I'd just like an idea of when it might be in for planning purposes. 😄

**Comment by guigrpa** [comment]
Right now I want to get some perf improvements out (`oao bootstrap`, so it will probably be useful to you as well on CI) and will probably release tonight (CET). I'll review this PR after that, I guess this week.

**Comment by guigrpa** [comment]
Out of curiosity, are you going to use it for an OSS project, or internally?

**Comment by guigrpa** [comment]
Out of curiosity (II): how do you tell Travis what kind of version bump you want (major, minor, patch, etc.)?

**Comment by gordlea** [comment]
@guigrpa we're planning on using it internally for now. If we release any oss we will consider it. 

I'm going have a script that does something like this:
1. Find the PR (using the github api) that was merged into master to kick off the current build.
2. Parse the title of that PR for [major], [minor], [patch]. If no increment is found in the title, default to minor.
3. Pass the parsed value to ` --increment-version-by`.

**Comment by gordlea** [comment]
If someone isn't using github, they could do something similar with changelogs or something.

**Comment by guigrpa** [comment]
LGTM, thanks for this improvement to oao and for the insight on your publishing process. I'll try to cut a new release in a few days.

**Pull request merged**
